//! `noeta.lock` — the reproducible dependency pin (package-manager P2.4c).
//!
//! After the graph walk ([`crate::graph`]) resolves the dependency graph, the resolved coordinates
//! are written here next to `noeta.toml`: each package's identity, version, source, and content hash.
//! A git package additionally pins the **commit SHA** its tag resolved to. On a later build the lock
//! is read back so a git dependency is fetched **by its pinned SHA** ([`crate::git::fetch_pinned`]) —
//! which, if the tree is already in the store, touches the network *not at all* (offline), and
//! otherwise verifies the tag still points at the pinned commit (reproducibility). The lock is a
//! generated file, meant to be committed; the walk remains the source of truth and refreshes it.
//!
//! The format is TOML, Cargo-like:
//! ```toml
//! version = 1
//!
//! [[package]]
//! name = "acme/greet"
//! version = "1.0.0"
//! source = "git"
//! url = "https://example.com/acme/greet"
//! tag = "v1.0.0"
//! sha = "…40 hex…"
//! hash = "…content hash…"
//! ```

use std::collections::BTreeMap;
use std::io;
use std::path::Path;

use crate::graph::{LockedPackage, ResolvedSource};

/// The lockfile name, alongside `noeta.toml`.
pub const LOCK_NAME: &str = "noeta.lock";

/// The lock format version. A lock written by a newer format is ignored (treated as absent) so an
/// older toolchain re-resolves rather than misreading it.
const LOCK_VERSION: i64 = 1;

/// A read lockfile: the pins a build consults to reproduce (package-manager P2.4c). Missing or
/// unreadable → [`Lock::empty`] (the walk then resolves from scratch).
#[derive(Debug, Default)]
pub struct Lock {
    /// `(git url, tag)` → pinned commit SHA.
    git_pins: BTreeMap<(String, String), String>,
    /// package identity → content hash (integrity check for immutable git sources).
    hashes: BTreeMap<String, String>,
}

impl Lock {
    /// An empty lock — no pins, so every dependency is resolved fresh.
    pub fn empty() -> Lock {
        Lock::default()
    }

    /// Read `dir/noeta.lock`, best-effort: a missing file, a parse error, or a version we don't
    /// understand all yield an empty lock (the build then re-resolves and rewrites it).
    pub fn read(dir: &Path) -> Lock {
        let Ok(text) = std::fs::read_to_string(dir.join(LOCK_NAME)) else {
            return Lock::empty();
        };
        let Ok(table) = text.parse::<toml::Table>() else {
            return Lock::empty();
        };
        if table.get("version").and_then(|v| v.as_integer()) != Some(LOCK_VERSION) {
            return Lock::empty();
        }
        let mut lock = Lock::empty();
        if let Some(packages) = table.get("package").and_then(|v| v.as_array()) {
            for entry in packages {
                let Some(pkg) = entry.as_table() else {
                    continue;
                };
                let get = |k: &str| pkg.get(k).and_then(|v| v.as_str());
                let (Some(name), Some(hash)) = (get("name"), get("hash")) else {
                    continue;
                };
                lock.hashes.insert(name.to_string(), hash.to_string());
                if let (Some(url), Some(tag), Some(sha)) = (get("url"), get("tag"), get("sha")) {
                    lock.git_pins
                        .insert((url.to_string(), tag.to_string()), sha.to_string());
                }
            }
        }
        lock
    }

    /// The pinned commit SHA for a git `url`@`tag`, if the lock records it.
    pub fn git_pin(&self, url: &str, tag: &str) -> Option<&str> {
        self.git_pins
            .get(&(url.to_string(), tag.to_string()))
            .map(String::as_str)
    }

    /// The recorded content hash for a package identity, if any.
    pub fn content_hash(&self, identity: &str) -> Option<&str> {
        self.hashes.get(identity).map(String::as_str)
    }
}

/// Serialize the resolved packages to `noeta.lock` text (deterministic, sorted by identity).
fn render(locked: &[LockedPackage]) -> String {
    let mut sorted: Vec<&LockedPackage> = locked.iter().collect();
    sorted.sort_by(|a, b| a.identity.cmp(&b.identity));
    let mut out = String::new();
    out.push_str("# This file is generated by noeta; it is meant to be committed. Do not edit.\n");
    out.push_str(&format!("version = {LOCK_VERSION}\n"));
    for pkg in sorted {
        out.push_str("\n[[package]]\n");
        out.push_str(&format!("name = {}\n", quote(&pkg.identity)));
        out.push_str(&format!("version = {}\n", quote(&pkg.version.to_string())));
        match &pkg.source {
            ResolvedSource::Path { path } => {
                out.push_str("source = \"path\"\n");
                out.push_str(&format!("path = {}\n", quote(&path.display().to_string())));
            }
            ResolvedSource::Git { url, tag, sha } => {
                out.push_str("source = \"git\"\n");
                out.push_str(&format!("url = {}\n", quote(url)));
                out.push_str(&format!("tag = {}\n", quote(tag)));
                out.push_str(&format!("sha = {}\n", quote(sha)));
            }
        }
        out.push_str(&format!("hash = {}\n", quote(&pkg.content_hash)));
    }
    out
}

/// Write `dir/noeta.lock` if its content would change (avoiding mtime churn on every run). Atomic
/// (temp file + rename). Best-effort at the call site: a read-only project shouldn't fail a build, so
/// the caller may ignore the error — but the error is returned so a dedicated verb (`noeta update`)
/// can surface it.
pub fn write(dir: &Path, locked: &[LockedPackage]) -> io::Result<()> {
    let path = dir.join(LOCK_NAME);
    let text = render(locked);
    if std::fs::read_to_string(&path).is_ok_and(|existing| existing == text) {
        return Ok(()); // unchanged
    }
    let tmp = dir.join(format!(".{LOCK_NAME}.{}.tmp", std::process::id()));
    std::fs::write(&tmp, &text)?;
    std::fs::rename(&tmp, &path)
}

/// Minimal TOML basic-string quoting for the values we emit (identities, versions, SHAs, URLs, and
/// paths). Escapes backslashes and double quotes; the values never contain control characters.
fn quote(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

#[cfg(test)]
mod tests {
    use super::*;
    use semver::Version;
    use std::path::PathBuf;

    fn git_pkg() -> LockedPackage {
        LockedPackage {
            identity: "acme/greet".to_string(),
            version: Version::new(1, 0, 0),
            content_hash: "deadbeef".to_string(),
            source: ResolvedSource::Git {
                url: "https://example.com/acme/greet".to_string(),
                tag: "v1.0.0".to_string(),
                sha: "a".repeat(40),
            },
        }
    }

    fn path_pkg() -> LockedPackage {
        LockedPackage {
            identity: "acme/local".to_string(),
            version: Version::new(0, 2, 0),
            content_hash: "cafe".to_string(),
            source: ResolvedSource::Path {
                path: PathBuf::from("../local"),
            },
        }
    }

    #[test]
    fn round_trips_pins_and_hashes() {
        let dir = std::env::temp_dir().join("noeta_lock_test_roundtrip");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        write(&dir, &[git_pkg(), path_pkg()]).unwrap();

        let lock = Lock::read(&dir);
        assert_eq!(
            lock.git_pin("https://example.com/acme/greet", "v1.0.0"),
            Some("a".repeat(40).as_str())
        );
        assert_eq!(lock.content_hash("acme/greet"), Some("deadbeef"));
        assert_eq!(lock.content_hash("acme/local"), Some("cafe"));
        // A path package records no git pin.
        assert_eq!(lock.git_pin("../local", ""), None);
    }

    #[test]
    fn rewrite_is_skipped_when_unchanged() {
        let dir = std::env::temp_dir().join("noeta_lock_test_nochurn");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        write(&dir, &[git_pkg()]).unwrap();
        let first = std::fs::metadata(dir.join(LOCK_NAME))
            .unwrap()
            .modified()
            .unwrap();
        // A no-op write must not touch the file (same content).
        write(&dir, &[git_pkg()]).unwrap();
        let second = std::fs::metadata(dir.join(LOCK_NAME))
            .unwrap()
            .modified()
            .unwrap();
        assert_eq!(first, second, "an unchanged lock must not be rewritten");
    }

    #[test]
    fn a_missing_or_bad_lock_reads_empty() {
        let dir = std::env::temp_dir().join("noeta_lock_test_missing");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        assert!(Lock::read(&dir).git_pin("x", "y").is_none());
        // A future version is ignored (re-resolve rather than misread).
        std::fs::write(dir.join(LOCK_NAME), "version = 999\n").unwrap();
        assert!(Lock::read(&dir).content_hash("acme/greet").is_none());
    }
}
