[package]
name = "noeta-diagnostics"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
noeta-span = { workspace = true }
ariadne = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
