[package]
name = "lang-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
lang-ast = { workspace = true }
lang-ir = { workspace = true }
lang-span = { workspace = true }
lang-diagnostics = { workspace = true }
lang-bytecode = { workspace = true }
lang-builtins = { workspace = true }
lang-object = { workspace = true }
lang-stdlib = { workspace = true }
lang-check = { workspace = true }

[dev-dependencies]
lang-lexer = { workspace = true }
lang-parser = { workspace = true }

[lints]
workspace = true
