//! The Rust half of the semver differential (audit row 4, item 5).
//!
//! `test_data/wire/semver-vectors.json` is generated by `cargo run -p noeta-pm --example
//! semver_vectors` and copied to the registry repo with the rest of the wire fixtures, where
//! `test/semver.test.ts` replays it against the hand-written TypeScript port in
//! `noeta-registry/src/semver.ts`. That is the point of the file: it is the only thing making "the
//! port agrees with `semver::VersionReq::matches`" a fact instead of a sentence in a comment
//! describing a throwaway binary that existed in neither repo.
//!
//! This side replays it against **the crate**, so the file cannot go stale in the other direction:
//! a `semver` upgrade that changes a corner case, or a hand-edit of the generated JSON, fails here
//! instead of quietly re-baselining what `noeta audit` means by "affected".
//!
//! Deliberately an **integration test with no feature gate**, like the other two cross-repo pins
//! (`tests/wire_fixture_manifest.rs`, `tests/publish_limits.rs`). The advisory chain, the log
//! verification and the wire round-trips all live behind `registry-http` / `provenance` and so run
//! only under `--all-features` — the gap that made roughly 40% of this crate's test surface dead
//! until CI was fixed. `semver` is a hard dependency and reading a file needs no crypto, so this one
//! runs in the plain `cargo test --workspace` step too.

use semver::{Version, VersionReq};

/// One generated case. Mirrors the JSON emitted by `examples/semver_vectors.rs`.
struct Vector {
    rule: String,
    version: String,
    req: String,
    /// `semver::VersionReq::matches`, or `None` when either string failed to parse.
    expected: Option<bool>,
    /// What `Advisory::affects` returns — the same answer with unknown collapsed to `false`.
    affects: bool,
}

fn vectors() -> Vec<Vector> {
    let path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("test_data/wire/semver-vectors.json");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|err| {
        panic!(
            "cannot read `{}`: {err} — regenerate it with `cargo run -p noeta-pm --example \
             semver_vectors > {}`",
            path.display(),
            path.display()
        )
    });
    let value: serde_json::Value = serde_json::from_str(&text).expect("semver-vectors.json");
    let cases = value["cases"].as_array().expect("`cases` array");
    cases
        .iter()
        .map(|c| Vector {
            rule: c["rule"].as_str().expect("rule").to_string(),
            version: c["version"].as_str().expect("version").to_string(),
            req: c["req"].as_str().expect("req").to_string(),
            expected: c["expected"].as_bool(), // JSON `null` → None, by construction
            affects: c["affects"].as_bool().expect("affects"),
        })
        .collect()
}

/// The generated answers ARE the crate's answers — re-derived, not trusted.
#[test]
fn semver_vectors_still_match_the_crate() {
    let cases = vectors();
    assert!(
        cases.len() > 50,
        "only {} vectors — the file looks truncated",
        cases.len()
    );
    let mut drifted = Vec::new();
    for c in &cases {
        let actual = Version::parse(&c.version)
            .ok()
            .zip(VersionReq::parse(&c.req).ok())
            .map(|(v, r)| r.matches(&v));
        if actual != c.expected {
            drifted.push(format!(
                "  {:?} vs {:?}: the file says {:?}, semver::VersionReq::matches says {:?}  [{}]",
                c.version, c.req, c.expected, actual, c.rule
            ));
        }
    }
    assert!(
        drifted.is_empty(),
        "{} of {} generated semver vectors no longer match the crate — the registry's hand port \
         (noeta-registry/src/semver.ts) is being checked against a stale baseline, so `noeta audit` \
         and the registry's \"affected?\" page can disagree. Regenerate with `cargo run -p noeta-pm \
         --example semver_vectors` and re-run BOTH suites:\n{}",
        drifted.len(),
        cases.len(),
        drifted.join("\n")
    );
}

/// The `affects` column is the client's actual verdict: unknown collapses to `false` so a malformed
/// advisory range fabricates no hit. Pinned separately because it is the asymmetry the TS port is
/// *allowed* to have — anywhere else the two columns differ would be a real disagreement.
#[test]
fn affects_is_the_match_result_with_unknown_collapsed() {
    for c in vectors() {
        assert_eq!(
            c.affects,
            c.expected.unwrap_or(false),
            "{:?} vs {:?} [{}]",
            c.version,
            c.req,
            c.rule
        );
    }
}

/// And that column is really what [`noeta_pm::advisory::Advisory::affects`] does — the function
/// `noeta audit` calls (`crates/noeta-cli/src/cmd/pm.rs`, the advisory section). Without this the
/// vectors would pin the *crate*, and `affects` could drift away from them in `advisory.rs`.
#[cfg(all(feature = "registry-http", feature = "provenance"))]
#[test]
fn advisory_affects_matches_every_vector() {
    for c in vectors() {
        let Ok(version) = Version::parse(&c.version) else {
            continue; // a version the resolver could never have produced
        };
        let advisory: noeta_pm::advisory::Advisory = serde_json::from_value(serde_json::json!({
            "id": "NOETA-0000-0000",
            "package": "acme/imgfx",
            "ranges": c.req,
            "severity": "high",
            "summary": "vector",
            "withdrawn": false,
            "seq": 0,
            "signature": "",
        }))
        .expect("advisory shape");
        assert_eq!(
            advisory.affects(&version),
            c.affects,
            "Advisory::affects({:?}, ranges={:?}) diverged from the generated vectors [{}]",
            c.version,
            c.req,
            c.rule
        );
    }
}
