[package]
name = "lang-bytecode"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
lang-ast = { workspace = true }
lang-stdlib = { workspace = true }
lang-span = { workspace = true }
lang-diagnostics = { workspace = true }
lang-object = { workspace = true }

[lints]
workspace = true
