//! The embedded example corpus and the lexical retrieval over it, plus doc-guide retrieval
//! delegated to [`noeta_ide::guide`].
//!
//! The language guides (`docs/*.md`) live in one embedded copy in `noeta-ide` (the docs-browser's
//! canonical loader), so the editor's docs browser and this server read the same pages through one
//! parser; the `docs_*` functions here are thin forwarders to it. The example programs
//! (`tests/conformance/**/*.noe`) are MCP-specific (they back `examples_find` /
//! `explain_diagnostic`, not the docs browser) and stay embedded here.
//!
//! Retrieval is dependency-free lexical scoring: the example corpus is small (~1,230 files), so a
//! term-frequency ranker is instant and good enough. An embedding index is a later refinement.
//!
//! The corpus is embedded as **one blob plus an integer index**, generated by `build.rs`, rather
//! than one `&'static str` per file — see that file for why (every embedded pointer is an `ld.so`
//! relocation paid at every process start, and this corpus owned 8.9% of the binary's total).

use noeta_ide::guide;
use std::path::Path;
use std::sync::OnceLock;

/// The whole example corpus as **one** blob: `path` bytes then source bytes, per file, back to
/// back. See `build.rs` — the point is that a blob holds no pointers, so 1,233 embedded files
/// cost two relocations at process start instead of ~4,700.
static EXAMPLES_BLOB: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/examples.blob"));

// `EXAMPLE_INDEX: &[[u32; 4]]` — one `[path_off, path_len, src_off, src_len]` row per file, in
// sorted path order. Plain integers, so it lands in `.rodata` and relocates nothing.
include!(concat!(env!("OUT_DIR"), "/examples_index.rs"));

/// `(relative path, source)` for every embedded example, in sorted path order.
fn embedded_examples() -> impl Iterator<Item = (&'static str, &'static str)> {
    EXAMPLE_INDEX
        .iter()
        .filter_map(|&[p_off, p_len, s_off, s_len]| {
            let slice = |off: u32, len: u32| {
                EXAMPLES_BLOB
                    .get(off as usize..(off + len) as usize)
                    .and_then(|b| str::from_utf8(b).ok())
            };
            Some((slice(p_off, p_len)?, slice(s_off, s_len)?))
        })
}

/// One example program (a `tests/conformance/**/*.noe` file).
#[derive(Debug)]
pub struct Example {
    /// The feature directory it lives under, e.g. `diagnostics`, `generics`.
    pub feature: String,
    /// The file stem, e.g. `type_mismatch`.
    pub name: String,
    /// The leading `//` comment block (the case's own description), directives stripped.
    pub description: String,
    /// The full source.
    pub code: &'static str,
    /// Every `E0xxx` code the case's `// expect:` directives reference (empty for a passing case).
    pub codes: Vec<String>,
}

struct Corpus {
    examples: Vec<Example>,
}

fn corpus() -> &'static Corpus {
    static CORPUS: OnceLock<Corpus> = OnceLock::new();
    CORPUS.get_or_init(|| Corpus {
        examples: load_examples(),
    })
}

fn load_examples() -> Vec<Example> {
    let mut examples: Vec<Example> = embedded_examples()
        .filter_map(|(rel, code)| {
            let path = Path::new(rel);
            let name = path.file_stem().and_then(|s| s.to_str())?;
            // The feature is the first path component under the corpus root; a file directly
            // in the root (rare) is filed under `root`.
            let feature = path
                .components()
                .next()
                .and_then(|c| c.as_os_str().to_str())
                .filter(|_| path.components().count() > 1)
                .unwrap_or("root")
                .to_string();
            Some(Example {
                feature,
                name: name.to_string(),
                description: leading_comment(code),
                code,
                codes: extract_codes(code),
            })
        })
        .collect();
    examples.sort_by(|a, b| (&a.feature, &a.name).cmp(&(&b.feature, &b.name)));
    examples
}

// ---- text helpers ----

/// The leading `//`-comment block of a `.noe` file — the case's own prose description — with the
/// comment markers and the machine-readable `expect:` directives stripped.
fn leading_comment(code: &str) -> String {
    let mut lines = Vec::new();
    for line in code.lines() {
        let trimmed = line.trim_start();
        if let Some(rest) = trimmed.strip_prefix("//") {
            let rest = rest.trim();
            // `// expect:` / `// expect-*:` directives are for the harness, not the reader.
            if rest.starts_with("expect") && rest.contains(':') {
                continue;
            }
            lines.push(rest.to_string());
        } else if trimmed.is_empty() && lines.is_empty() {
            continue; // leading blank lines
        } else {
            break; // first non-comment line ends the header block
        }
    }
    lines.join(" ").trim().to_string()
}

/// Every `E0xxx` code mentioned in `text` (deduplicated, in first-seen order). Scans for `E`
/// followed by 3+ digits — matches both the `// expect: error E0007` directives and any prose.
fn extract_codes(text: &str) -> Vec<String> {
    let bytes = text.as_bytes();
    let mut codes = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'E' {
            let mut j = i + 1;
            while j < bytes.len() && bytes[j].is_ascii_digit() {
                j += 1;
            }
            if j - (i + 1) >= 3 {
                let code = text[i..j].to_string();
                if !codes.contains(&code) {
                    codes.push(code);
                }
                i = j;
                continue;
            }
        }
        i += 1;
    }
    codes
}

/// Split a query into lowercased search terms (length ≥ 2), deduplicated.
fn terms(query: &str) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for raw in query.split(|c: char| !c.is_alphanumeric()) {
        let t = raw.to_lowercase();
        if t.len() >= 2 && !out.contains(&t) {
            out.push(t);
        }
    }
    out
}

fn count_occurrences(haystack_lower: &str, needle: &str) -> u32 {
    haystack_lower.matches(needle).count() as u32
}

// ---- public retrieval API ----

/// A `docs_search` hit (already ranked best-first). Mirrors the fields the MCP tool surfaces from
/// [`noeta_ide::guide::GuideHit`], kept as the tool's own wire type so the tool layer stays
/// decoupled from the engine type. (The ranking score is internal to the guide ranker and not
/// surfaced, so it is dropped here.)
#[derive(Debug, Clone)]
pub struct DocHit {
    pub page: String,
    pub title: String,
    pub heading: String,
    pub anchor: String,
    pub snippet: String,
}

/// Rank guide sections against `query`; returns the top `limit` hits (best-first) — delegated to
/// the shared [`noeta_ide::guide`] corpus (one embedded copy, one ranker, shared with the editor's
/// docs browser).
pub fn search_docs(query: &str, limit: usize) -> Vec<DocHit> {
    guide::search(query, limit)
        .into_iter()
        .map(|h| DocHit {
            page: h.page,
            title: h.title,
            heading: h.heading,
            anchor: h.anchor,
            snippet: h.snippet,
        })
        .collect()
}

/// The full markdown of the guide page whose slug or title matches `name` (see
/// [`noeta_ide::guide::get_page`]).
pub fn get_doc(name: &str) -> Option<&'static str> {
    guide::get_page(name)
}

/// The `(slug, title)` of every guide page — powers resource listing and a bare `docs_get`.
pub fn doc_index() -> Vec<(String, String)> {
    guide::index()
}

/// An `examples_find` hit.
#[derive(Debug, Clone)]
pub struct ExampleHit {
    pub feature: String,
    pub name: String,
    pub description: String,
    pub code: String,
    pub codes: Vec<String>,
    pub score: u32,
}

/// Rank example programs against `query` (matched against feature, name, description, codes, and
/// source); returns the top `limit` hits. A query that names a feature dir strongly boosts it.
pub fn search_examples(query: &str, limit: usize) -> Vec<ExampleHit> {
    let terms = terms(query);
    if terms.is_empty() {
        return Vec::new();
    }
    let mut hits: Vec<ExampleHit> = corpus()
        .examples
        .iter()
        .filter_map(|e| {
            let feature_l = e.feature.to_lowercase();
            let name_l = e.name.to_lowercase();
            let desc_l = e.description.to_lowercase();
            let code_l = e.code.to_lowercase();
            let codes_l = e.codes.join(" ").to_lowercase();
            let mut score = 0;
            for t in &terms {
                score += count_occurrences(&feature_l, t) * 5;
                score += count_occurrences(&name_l, t) * 4;
                score += count_occurrences(&codes_l, t) * 4;
                score += count_occurrences(&desc_l, t) * 2;
                // Source matches count once per term (presence), not per occurrence, so a long file
                // that merely mentions a term does not dominate a focused example.
                if code_l.contains(t) {
                    score += 1;
                }
            }
            (score > 0).then(|| example_hit(e, score))
        })
        .collect();
    hits.sort_by(|a, b| {
        b.score
            .cmp(&a.score)
            .then((&a.feature, &a.name).cmp(&(&b.feature, &b.name)))
    });
    hits.truncate(limit);
    hits
}

/// Every example whose `// expect:` directives reference `code` (e.g. `E0007`) — the real,
/// CI-tested programs that trigger a diagnostic. Powers `explain_diagnostic`.
pub fn examples_for_code(code: &str) -> Vec<ExampleHit> {
    let mut hits: Vec<ExampleHit> = corpus()
        .examples
        .iter()
        .filter(|e| e.codes.iter().any(|c| c == code))
        .map(|e| example_hit(e, 0))
        .collect();
    // The `diagnostics/` cases are the canonical minimal repros for a code — surface them first,
    // then the incidental cases (a passing feature test that also happens to raise the code).
    hits.sort_by(|a, b| {
        let a_key = (a.feature != "diagnostics", &a.feature, &a.name);
        let b_key = (b.feature != "diagnostics", &b.feature, &b.name);
        a_key.cmp(&b_key)
    });
    hits
}

/// The source of the example at `feature/name`, if it exists. Powers `noeta-example://` resource
/// reads (an agent can pin a specific example surfaced by `examples_find`).
pub fn get_example(feature: &str, name: &str) -> Option<&'static str> {
    corpus()
        .examples
        .iter()
        .find(|e| e.feature == feature && e.name == name)
        .map(|e| e.code)
}

/// Guide pages whose body mentions `code`, as `(slug, title)`. Powers `explain_diagnostic`'s links.
pub fn docs_mentioning(code: &str) -> Vec<(String, String)> {
    guide::pages_mentioning(code)
}

fn example_hit(e: &Example, score: u32) -> ExampleHit {
    ExampleHit {
        feature: e.feature.clone(),
        name: e.name.clone(),
        description: e.description.clone(),
        code: e.code.to_string(),
        codes: e.codes.clone(),
        score,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn docs_load_and_have_titles() {
        let idx = doc_index();
        assert!(
            idx.len() > 20,
            "expected the full docs corpus, got {}",
            idx.len()
        );
        assert!(idx.iter().all(|(_, title)| !title.is_empty()));
        // A known page resolves by a fuzzy name.
        assert!(get_doc("type system").is_some());
    }

    #[test]
    fn docs_search_ranks_relevant_pages() {
        // Delegates to the shared guide ranker, which returns hits best-first.
        let hits = search_docs("pattern matching", 5);
        assert!(!hits.is_empty(), "expected hits for 'pattern matching'");
        assert!(!hits[0].snippet.is_empty());
        assert!(hits.len() <= 5);
    }

    #[test]
    fn examples_load_and_parse_expect_codes() {
        let for_e0007 = examples_for_code("E0007");
        assert!(
            for_e0007.iter().any(|e| e.name == "type_mismatch"),
            "type_mismatch.noe should be indexed under E0007"
        );
        let ex = for_e0007
            .iter()
            .find(|e| e.name == "type_mismatch")
            .unwrap();
        assert!(
            !ex.description.is_empty(),
            "the header comment is the description"
        );
        assert!(
            !ex.description.contains("expect:"),
            "directives are stripped"
        );
    }

    #[test]
    fn examples_find_matches_feature_and_content() {
        let hits = search_examples("generics", 10);
        assert!(!hits.is_empty());
        assert!(hits.iter().any(|h| h.feature == "generics"));
    }

    #[test]
    fn extract_codes_finds_all_e_codes() {
        assert_eq!(extract_codes("error E0007 at 6:6"), vec!["E0007"]);
        assert_eq!(
            extract_codes("E0007 then E0007 then E0011"),
            vec!["E0007", "E0011"]
        );
        assert!(extract_codes("no codes here E12").is_empty());
    }
}
