#!/usr/bin/env python3
"""Regenerate the delimiter-nesting conformance cases.

The pair of cases these write straddle `noeta_parser::MAX_NESTING_DEPTH`: one file sits exactly on
the limit and must parse and run, one sits a single level past it and must report E0032. They are
generated rather than written because the limit moves — it is derived from a *measured* per-level
stack cost (`STACK_PER_NESTING_LEVEL`), so a grammar change that makes parser frames heavier can
lower it — and because 128 levels of nesting is not something to maintain by hand.

    python3 scripts/gen-nesting-cases.py [LIMIT]

LIMIT defaults to the `MAX_NESTING_DEPTH` read out of the parser source, so the usual invocation is
bare: edit the constant, run this, and the corpus follows.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PARSER = ROOT / "crates" / "noeta-parser" / "src" / "lib.rs"
CASES = ROOT / "tests" / "conformance" / "diagnostics"


def limit_from_source() -> int:
    m = re.search(r"^const MAX_NESTING_DEPTH: usize = (\d+);", PARSER.read_text(), re.M)
    if not m:
        raise SystemExit(f"could not find MAX_NESTING_DEPTH in {PARSER}")
    return int(m.group(1))


def brackets(depth: int) -> str:
    """`x = [[[…1…]]]` — `depth` levels of list literal, the cheapest deep shape."""
    return f"x = {'[' * depth}1{']' * depth};"


def write(name: str, lines: list[str]) -> None:
    path = CASES / name
    path.write_text("\n".join(lines) + "\n")
    print(f"wrote {path.relative_to(ROOT)} ({len(lines)} lines)")


def main() -> None:
    limit = int(sys.argv[1]) if len(sys.argv) > 1 else limit_from_source()

    # The accepting side. `echo` so the case has a runtime observable and the whole pipeline —
    # parse, check, eval — is proven to survive the deepest legal input, not just the parser.
    write(
        "nesting_at_the_limit.noe",
        [
            f"// Exactly `MAX_NESTING_DEPTH` ({limit}) delimiter levels: the deepest input the parser accepts.",
            "// It parses, checks and runs like any other program — the limit is where E0032 *starts*, so",
            "// the level below it has to stay ordinary. Generated by `scripts/gen-nesting-cases.py`; the",
            "// companion `nesting_too_deep.noe` is the same shape one level deeper.",
            "//",
            "// The pairing matters because the limit is not a round number chosen for looks: it is",
            "// `DEEP_PARSE_STACK` divided by a measured worst-case stack cost per nesting level. A file at",
            "// the limit that aborts the process instead of running is the failure this case exists to",
            "// catch, and it is a failure only the accepting side can see.",
            f'// expect: stdout "{limit}"',
            "// expect: exit 0",
            brackets(limit),
            f"echo {limit};",
        ],
    )

    # The rejecting side. The offending token is the (limit+1)th `[`, the first one past the limit;
    # `x = ` puts the first `[` in column 5.
    header = [
        "// A pathologically deep expression is rejected with a stable code (E0032) instead of overflowing",
        "// the recursive-descent parser stack — a crash the module loader's parse-error recovery cannot",
        f"// catch. The limit is `MAX_NESTING_DEPTH` ({limit}) delimiter levels, so the {limit + 1}th open bracket is",
        "// the offending position.",
        "//",
        "// Generated by `scripts/gen-nesting-cases.py`, alongside `nesting_at_the_limit.noe` — the same",
        "// shape one level shallower, which must parse and run. Together they pin the boundary from both",
        "// sides, so moving the limit has to move both files and cannot quietly turn back into a crash.",
    ]
    line = len(header) + 3  # + the two `expect:` lines + 1 for a 1-based index
    write(
        "nesting_too_deep.noe",
        header
        + [
            f"// expect: error E0032 at {line}:{5 + limit}",
            "// expect: exit 1",
            brackets(limit + 1),
        ],
    )


if __name__ == "__main__":
    main()
