#!/usr/bin/env python3
"""Regenerate the parser's recursion-limit conformance cases.

Each pair of cases these write straddles one of the parser's recursion limits: one file sits exactly
on the limit and must parse and run, one sits a single step past it and must report E0032. They are
generated rather than written because every limit moves — each is derived from a *measured* per-level
stack cost, so a grammar change that makes frames heavier can lower it — and because 128 levels of
nesting (let alone 512 `else if` branches) is not something to maintain by hand.

Three limits, three pairs:

* `MAX_NESTING_DEPTH` — delimiter nesting: `nesting_{at_the_limit,too_deep}.noe`.
* `MAX_ELSE_CHAIN_BRANCHES` — the statement chain `if … else if …`:
  `else_chain_{at_the_limit,too_long}.noe`. A chain is *flat* in delimiters (depth 2 however long it
  gets) but right-nested in the AST, so it needs a budget of its own.
* `MAX_TERNARY_CHAIN_BRANCHES` — the conditional-expression chain `if … then … else if …`:
  `ternary_chain_{at_the_limit,too_long}.noe`. The same shape at roughly twice the cost per branch
  (it desugars to a nested `match`), hence the stricter limit.

    python3 scripts/gen-nesting-cases.py

Every limit is read out of the parser source, so the usual invocation is bare: edit the constant, run
this, and the corpus follows.
"""

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
PARSER = ROOT / "crates" / "noeta-parser" / "src" / "lib.rs"
CASES = ROOT / "tests" / "conformance" / "diagnostics"
SOURCE = PARSER.read_text()


def literal(name: str) -> int:
    """A `const NAME: usize = <int literal>;` out of the parser source."""
    m = re.search(rf"^(?:pub )?const {name}: usize = (\d+);", SOURCE, re.M)
    if not m:
        raise SystemExit(f"could not find {name} in {PARSER}")
    return int(m.group(1))


def bytes_constant(name: str) -> int:
    """A `const NAME: usize = N * 1024[ * 1024];` byte constant out of the parser source."""
    m = re.search(rf"^(?:pub )?const {name}: usize = ([\d *]+?);", SOURCE, re.M)
    if not m:
        raise SystemExit(f"could not find {name} in {PARSER}")
    product = 1
    for factor in m.group(1).split("*"):
        product *= int(factor.strip())
    return product


def chain_limit(cost: str) -> int:
    """A chain limit, recomputed from the operands of its derivation in the parser source.

    The chain limits are written as `MIN_PIPELINE_STACK / <cost>` rather than as a literal, so that
    the derivation is visible where it is defined; reproducing the division here (instead of pattern
    matching the resulting number) keeps this script honest when either operand moves.
    """
    return bytes_constant("MIN_PIPELINE_STACK") // bytes_constant(cost)


def brackets(depth: int) -> str:
    """`x = [[[…1…]]]` — `depth` levels of list literal, the cheapest deep shape."""
    return f"x = {'[' * depth}1{']' * depth};"


def else_chain(branches: int) -> list[str]:
    """A dispatch fn whose body is one `if`/`else if` chain of `branches` branches.

    Delimiter depth is 2 at every length, which is exactly why the depth limit cannot bound it.
    """
    lines = ["fn dispatch(a: int): int {", "  if a == 0 {", "    return 0"]
    for i in range(1, branches):
        lines += [f"  }} else if a == {i} {{", f"    return {i}"]
    lines += ["  } else {", "    return -1", "  }", "}"]
    return lines


def ternary_chain(branches: int) -> str:
    """`x = if a == 0 then 0 else if a == 1 then 1 else … else -1;` — `branches` branches."""
    arms = "".join(f"if a == {i} then {i} else " for i in range(branches))
    return f"x = {arms}-1;"


def write(name: str, lines: list[str]) -> None:
    path = CASES / name
    path.write_text("\n".join(lines) + "\n")
    print(f"wrote {path.relative_to(ROOT)} ({len(lines)} lines)")


def nesting_cases(limit: int) -> None:
    # The accepting side. `echo` so the case has a runtime observable and the whole pipeline —
    # parse, check, eval — is proven to survive the deepest legal input, not just the parser.
    write(
        "nesting_at_the_limit.noe",
        [
            f"// Exactly `MAX_NESTING_DEPTH` ({limit}) delimiter levels: the deepest input the parser accepts.",
            "// It parses, checks and runs like any other program — the limit is where E0032 *starts*, so",
            "// the level below it has to stay ordinary. Generated by `scripts/gen-nesting-cases.py`; the",
            "// companion `nesting_too_deep.noe` is the same shape one level deeper.",
            "//",
            "// The pairing matters because the limit is not a round number chosen for looks: it is",
            "// `DEEP_PARSE_STACK` divided by a measured worst-case stack cost per nesting level. A file at",
            "// the limit that aborts the process instead of running is the failure this case exists to",
            "// catch, and it is a failure only the accepting side can see.",
            f'// expect: stdout "{limit}"',
            "// expect: exit 0",
            brackets(limit),
            f"echo {limit};",
        ],
    )

    # The rejecting side. The offending token is the (limit+1)th `[`, the first one past the limit;
    # `x = ` puts the first `[` in column 5.
    header = [
        "// A pathologically deep expression is rejected with a stable code (E0032) instead of overflowing",
        "// the recursive-descent parser stack — a crash the module loader's parse-error recovery cannot",
        f"// catch. The limit is `MAX_NESTING_DEPTH` ({limit}) delimiter levels, so the {limit + 1}th open bracket is",
        "// the offending position.",
        "//",
        "// Generated by `scripts/gen-nesting-cases.py`, alongside `nesting_at_the_limit.noe` — the same",
        "// shape one level shallower, which must parse and run. Together they pin the boundary from both",
        "// sides, so moving the limit has to move both files and cannot quietly turn back into a crash.",
    ]
    line = len(header) + 3  # + the two `expect:` lines + 1 for a 1-based index
    write(
        "nesting_too_deep.noe",
        header
        + [
            f"// expect: error E0032 at {line}:{5 + limit}",
            "// expect: exit 1",
            brackets(limit + 1),
        ],
    )


def else_chain_cases(limit: int) -> None:
    # The accepting side, and the one that carries the weight: this shape used to abort the process at
    # ~725 branches with no diagnostic, so a limit the pipeline cannot actually deliver would be the
    # same crash under a new name. It runs end to end — `echo dispatch(…)` — because the parser is not
    # the binding stage here; `noeta run`'s recursive Core-IR pipeline is.
    write(
        "else_chain_at_the_limit.noe",
        [
            f"// Exactly `MAX_ELSE_CHAIN_BRANCHES` ({limit}) branches in one `if`/`else if` chain: the longest",
            "// the parser accepts. An `else if` chain is right-nested in the AST (each `else` holds the next",
            "// `if`) but FLAT in delimiters — it sits at depth 2 however long it gets — so `MAX_NESTING_DEPTH`",
            "// never saw it, and ~725 branches used to overflow the stack with no diagnostic at all.",
            "//",
            "// Generated by `scripts/gen-nesting-cases.py`; the companion `else_chain_too_long.noe` is the",
            "// same shape one branch longer. The accepting side runs the whole pipeline (parse, check, lower,",
            "// eval), which is the point: the parser's own recursion per branch is gone (the `if` grammar is",
            "// iterative), so the stages downstream of it are what the limit is derived from, and only a case",
            "// that executes can catch a limit they cannot hold.",
            '// expect: stdout "7"',
            "// expect: exit 0",
        ]
        + else_chain(limit)
        + ["echo dispatch(7);"],
    )

    # The rejecting side. The offending token is the `if` of the (limit+1)th branch.
    header = [
        f"// One branch past `MAX_ELSE_CHAIN_BRANCHES` ({limit}): rejected with a stable code (E0032) rather",
        "// than overflowing the stack somewhere downstream of the parser. It is the same code deep",
        "// delimiter nesting gets, because a chain IS nesting — there is just no delimiter to count, which",
        "// is how this shape escaped the depth limit in the first place.",
        "//",
        "// Generated by `scripts/gen-nesting-cases.py`, alongside `else_chain_at_the_limit.noe` — the same",
        "// shape one branch shorter, which must parse, check and run. Together they pin the boundary from",
        "// both sides, so moving the limit has to move both files and cannot quietly turn back into a crash.",
    ]
    body = else_chain(limit + 1)
    # `  } else if a == <limit> {` is the last continuation; its `if` is the offending token, at
    # column 10 (1-based) of that line, which is the second-to-last `}`/`else`/`return` triple.
    offending_line = len(header) + 2 + body.index(f"  }} else if a == {limit} {{") + 1
    write(
        "else_chain_too_long.noe",
        header
        + [
            f"// expect: error E0032 at {offending_line}:10",
            "// expect: exit 1",
        ]
        + body,
    )


def ternary_chain_cases(limit: int) -> None:
    write(
        "ternary_chain_at_the_limit.noe",
        [
            f"// Exactly `MAX_TERNARY_CHAIN_BRANCHES` ({limit}) branches in one `if … then … else if …` chain:",
            "// the longest conditional *expression* chain the parser accepts. Same right-nesting as the",
            "// statement chain, roughly twice the cost per branch — this form desugars to a nested `match`",
            "// per branch — so it gets its own, stricter limit, and the pre-pass tells the two apart by the",
            "// `then`. Pricing them together at the cheaper cost is exactly how a chain at the *statement*",
            "// limit still overflowed after the statement chain had been bounded.",
            "//",
            "// Generated by `scripts/gen-nesting-cases.py`; the companion `ternary_chain_too_long.noe` is the",
            "// same shape one branch longer.",
            '// expect: stdout "7"',
            "// expect: exit 0",
            "a = 7;",
            ternary_chain(limit),
            "echo x;",
        ],
    )

    header = [
        f"// One branch past `MAX_TERNARY_CHAIN_BRANCHES` ({limit}): rejected with E0032 rather than",
        "// overflowing the stack. The conditional-expression chain's limit is stricter than the statement",
        "// chain's because a branch of it costs the pipeline about twice as much.",
        "//",
        "// Generated by `scripts/gen-nesting-cases.py`, alongside `ternary_chain_at_the_limit.noe` — the",
        "// same shape one branch shorter, which must parse, check and run.",
    ]
    # `x = ` is 4 columns, then `limit` branches of `if a == <i> then <i> else `; the offending token
    # is the `if` opening the (limit+1)th branch. The chain is on the line after the two `expect:`
    # lines and the `a = 7;` setup, hence the +4.
    prefix = "".join(f"if a == {i} then {i} else " for i in range(limit))
    write(
        "ternary_chain_too_long.noe",
        header
        + [
            f"// expect: error E0032 at {len(header) + 4}:{5 + len(prefix)}",
            "// expect: exit 1",
            "a = 7;",
            ternary_chain(limit + 1),
        ],
    )


def main() -> None:
    nesting_cases(literal("MAX_NESTING_DEPTH"))
    else_chain_cases(chain_limit("STACK_PER_ELSE_CHAIN_BRANCH"))
    ternary_chain_cases(chain_limit("STACK_PER_TERNARY_CHAIN_BRANCH"))


if __name__ == "__main__":
    main()
