[package]
name = "noeta-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
noeta-edition = { workspace = true }
noeta-span = { workspace = true }
noeta-diagnostics = { workspace = true }
noeta-ast = { workspace = true }
noeta-lexer = { workspace = true }
chumsky = { workspace = true }
stacker = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
proptest = { workspace = true }

[lints]
workspace = true
