//! `noeta grammar` — emit editor grammar artifacts for a project's declared tiers.
//!
//! Noeta's tier blocks `@name { … }` may open a **verbatim** text body (`@doc`, or any
//! `@tier(<name>, text: "<lang>")` a project or extension declares) whose contents the compiler
//! never lexes as code. A *static* tree-sitter grammar cannot know which `@name`s open such a body
//! in a given project — extensions and programs declare their own — so it recognizes only the std
//! default (`doc`) and mis-parses the rest as code. This verb closes that gap for tree-sitter,
//! mirroring the VS Code extension's `generated-tiers.tmLanguage.json` generator on the TextMate
//! side (`editors/vscode-noeta/src/tierHighlighting.js`): it scans the project's declared tiers and
//! emits, for the tree-sitter grammar,
//!
//! * `project-tiers.json` — the verbatim-body tier-name token list `grammar.js` reads to widen its
//!   text-tier set (absent the file, `grammar.js` falls back to the static `doc`-only set), and
//! * `queries/injections.scm` — one language-injection rule per tier, so each verbatim body is
//!   highlighted with its declared language.
//!
//! The build step that turns the widened `grammar.js` into a parser is `tree-sitter generate` (run
//! for the caller with `--generate`, or by hand). The static grammar stays the fallback for a
//! project that declares no custom tiers.
//!
//! Unlike the TextMate generator's own regex scan, the tier set here comes from the compiler's
//! authoritative discovery — the same `noeta_lexer::declared_tier_languages_in` scan `noeta fmt`
//! uses — plus installed native extensions' tiers, so the editor grammar and the compiler agree on
//! which bodies are verbatim by construction.

use std::collections::BTreeMap;
use std::path::Path;
use std::process::ExitCode;

use noeta_span::{Source, SourceId};

use super::fmt::collect_noe_files;

/// The std default text tier every project has — its `@doc { … }` body is markdown.
const DEFAULT_TIER: (&str, &str) = ("doc", "markdown");

/// The provenance banner stamped into every generated artifact.
const GENERATED_HEADER: &str = "GENERATED by `noeta grammar tree-sitter` from the project's `@tier(name, text: \"lang\")` declarations. Do not edit — regenerate on change.";

/// Whether a tier's body is fully verbatim (a text tier — `${` is literal) or verbatim text with
/// `${ … }` code holes (an expression tier). The generated `grammar.js` routes each to a different
/// rule (`text_tier_block` vs `expr_tier_block`), so the two must be listed separately in the
/// overlay.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub(crate) enum TierKind {
    #[default]
    Text,
    Expr,
}

/// A verbatim-body tier the generated grammar must recognize, with its optional injection language
/// and whether it is a text or expression tier.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct TierEntry {
    pub name: String,
    pub language: Option<String>,
    pub kind: TierKind,
}

/// Whether `id` is a valid tree-sitter / Noeta identifier — a malformed declaration can never leak
/// into the generated `grammar.js` (executed as JavaScript) or an injection query.
fn is_ident(id: &str) -> bool {
    let mut chars = id.chars();
    matches!(chars.next(), Some(c) if c == '_' || c.is_ascii_alphabetic())
        && chars.all(|c| c == '_' || c.is_ascii_alphanumeric())
}

/// Canonicalize a raw `(tier name, optional body language)` set into the deterministic, deduplicated,
/// name-sorted list the generator emits. `doc → markdown` (the std default text tier) is always
/// present. Invalid identifiers are dropped. The result is a pure function of the *set* of inputs —
/// independent of their order and multiplicity — so the emitted grammar is byte-stable.
pub(crate) fn canonical_tiers(
    raw: impl IntoIterator<Item = (String, Option<String>)>,
) -> Vec<TierEntry> {
    let mut by_name: BTreeMap<String, Option<String>> = BTreeMap::new();
    let mut insert = |name: String, lang: Option<String>| {
        if !is_ident(&name) {
            return;
        }
        let lang = lang.filter(|l| is_ident(l));
        let slot = by_name.entry(name).or_default();
        // Merge deterministically: prefer a language, and the lexicographically smallest when two
        // declarations disagree — so the output never depends on scan order.
        *slot = match (slot.take(), lang) {
            (Some(a), Some(b)) => Some(a.min(b)),
            (Some(a), None) => Some(a),
            (None, b) => b,
        };
    };
    insert(DEFAULT_TIER.0.to_string(), Some(DEFAULT_TIER.1.to_string()));
    for (name, lang) in raw {
        insert(name, lang);
    }
    by_name
        .into_iter()
        .map(|(name, language)| TierEntry {
            name,
            language,
            kind: TierKind::Text,
        })
        .collect()
}

/// Canonicalize the **expression tiers** — like [`canonical_tiers`] but tagged [`TierKind::Expr`]
/// and with no default entry (there is no std expression tier the way `doc` is the std text tier).
/// The optional language is the between-holes prose language (for an injection), if the tier
/// declares one.
pub(crate) fn canonical_expr_tiers(
    raw: impl IntoIterator<Item = (String, Option<String>)>,
) -> Vec<TierEntry> {
    let mut by_name: BTreeMap<String, Option<String>> = BTreeMap::new();
    for (name, lang) in raw {
        if !is_ident(&name) {
            continue;
        }
        let lang = lang.filter(|l| is_ident(l));
        let slot = by_name.entry(name).or_default();
        *slot = match (slot.take(), lang) {
            (Some(a), Some(b)) => Some(a.min(b)),
            (Some(a), None) => Some(a),
            (None, b) => b,
        };
    }
    by_name
        .into_iter()
        .map(|(name, language)| TierEntry {
            name,
            language,
            kind: TierKind::Expr,
        })
        .collect()
}

/// The `project-tiers.json` content: the two tier-name token lists `grammar.js` consumes —
/// `textTiers` (fully-verbatim bodies) and `exprTiers` (verbatim text with `${…}` holes).
pub(crate) fn project_tiers_json(tiers: &[TierEntry]) -> String {
    let list = |kind: TierKind| -> String {
        tiers
            .iter()
            .filter(|t| t.kind == kind)
            .map(|t| format!("    {:?}", t.name))
            .collect::<Vec<_>>()
            .join(",\n")
    };
    format!(
        "{{\n  \"$comment\": {GENERATED_HEADER:?},\n  \"textTiers\": [\n{}\n  ],\n  \"exprTiers\": [\n{}\n  ]\n}}\n",
        list(TierKind::Text),
        list(TierKind::Expr),
    )
}

/// The `queries/injections.scm` content: one tree-sitter language-injection rule per tier with a
/// declared body language. A text tier injects its whole verbatim body; an expression tier injects
/// each between-holes `text_segment` (the holes stay Noeta code), so e.g. an `@html { … ${x} … }`
/// tier's prose highlights as HTML while `${x}` highlights as an expression.
pub(crate) fn injections_scm(tiers: &[TierEntry]) -> String {
    let mut out = format!(
        "; {GENERATED_HEADER}\n; Maps each tier body to its declared language for editor injection.\n",
    );
    for t in tiers {
        let Some(lang) = &t.language else { continue };
        match t.kind {
            TierKind::Text => out.push_str(&format!(
                "\n((text_tier_block\n   name: (identifier) @_tier\n   body: (text_block (text_body) @injection.content))\n (#eq? @_tier {:?})\n (#set! injection.language {lang:?}))\n",
                t.name,
            )),
            TierKind::Expr => out.push_str(&format!(
                "\n((expr_tier_block\n   name: (identifier) @_tier\n   (text_segment) @injection.content)\n (#eq? @_tier {:?})\n (#set! injection.language {lang:?}))\n",
                t.name,
            )),
        }
    }
    out
}

/// Collect the project's verbatim-body tiers: every `@tier(<name>, text: "<lang>")` declared in a
/// `.noe` file under `project` (or `project` itself if it is a `.noe` file), plus every installed
/// native extension's text/expression tier. Mirrors `noeta fmt`'s per-directory tier discovery (the
/// single authoritative scan), so the editor grammar agrees with the compiler on which bodies are
/// verbatim.
pub(crate) fn collect_project_tiers(project: &Path) -> Vec<TierEntry> {
    let mut text_raw: Vec<(String, Option<String>)> = Vec::new();
    let mut expr_raw: Vec<(String, Option<String>)> = Vec::new();
    let mut files = Vec::new();
    if project.is_dir() {
        collect_noe_files(project, &mut files);
    } else if project.extension().is_some_and(|e| e == "noe") {
        files.push(project.to_path_buf());
    }
    for path in files {
        if let Ok(text) = std::fs::read_to_string(&path) {
            let source = Source::new(SourceId(0), path.to_string_lossy().into_owned(), text);
            let lexed = noeta_lexer::lex(&source);
            // `expr:` is the discriminant: an expression tier carries `${…}` holes, and may also
            // declare a `text:` language for its between-holes prose (its segment injection). A tier
            // with only `text:` is a fully-verbatim text tier.
            let langs: std::collections::HashMap<String, String> =
                noeta_lexer::declared_tier_languages_in(&source, &lexed.tokens)
                    .into_iter()
                    .collect();
            let expr_names = noeta_lexer::declared_expr_tier_names_in(&source, &lexed.tokens);
            for name in &expr_names {
                expr_raw.push((name.clone(), langs.get(name).cloned()));
            }
            for (name, lang) in langs {
                if !expr_names.contains(&name) {
                    text_raw.push((name, Some(lang)));
                }
            }
        }
    }
    // Installed native extensions' tiers (no `.noe` file declares a native one). `expr` marks an
    // expression tier (its `text` is the between-holes segment language, if any); `text`-only is a
    // verbatim text tier.
    for t in noeta_stdlib::registry::ext_tiers() {
        if t.expr.is_some() {
            expr_raw.push((t.name.to_string(), t.text.map(str::to_string)));
        } else if t.text.is_some() {
            text_raw.push((t.name.to_string(), t.text.map(str::to_string)));
        }
    }
    let mut tiers = canonical_tiers(text_raw);
    tiers.extend(canonical_expr_tiers(expr_raw));
    tiers
}

/// `noeta grammar tree-sitter` — emit the per-project tree-sitter grammar artifacts.
pub(crate) fn cmd_grammar_treesitter(
    project: &Path,
    out: Option<&Path>,
    generate: bool,
) -> ExitCode {
    let tiers = collect_project_tiers(project);
    let json = project_tiers_json(&tiers);

    let Some(out) = out else {
        // No output dir: print the token list to stdout (for inspection / piping).
        print!("{json}");
        return ExitCode::SUCCESS;
    };

    if let Err(e) = std::fs::create_dir_all(out) {
        eprintln!("noeta grammar: cannot create `{}`: {e}", out.display());
        return ExitCode::FAILURE;
    }
    let tiers_path = out.join("project-tiers.json");
    if let Err(e) = std::fs::write(&tiers_path, &json) {
        eprintln!(
            "noeta grammar: cannot write `{}`: {e}",
            tiers_path.display()
        );
        return ExitCode::FAILURE;
    }
    let queries_dir = out.join("queries");
    if let Err(e) = std::fs::create_dir_all(&queries_dir) {
        eprintln!(
            "noeta grammar: cannot create `{}`: {e}",
            queries_dir.display()
        );
        return ExitCode::FAILURE;
    }
    let inj_path = queries_dir.join("injections.scm");
    if let Err(e) = std::fs::write(&inj_path, injections_scm(&tiers)) {
        eprintln!("noeta grammar: cannot write `{}`: {e}", inj_path.display());
        return ExitCode::FAILURE;
    }

    let names: Vec<&str> = tiers.iter().map(|t| t.name.as_str()).collect();
    eprintln!(
        "noeta grammar: wrote {} ({} verbatim tier{}: {})",
        tiers_path.display(),
        names.len(),
        if names.len() == 1 { "" } else { "s" },
        names.join(", "),
    );

    if generate {
        return run_tree_sitter_generate(out);
    }
    eprintln!(
        "noeta grammar: run `tree-sitter generate` in `{}` to rebuild the parser.",
        out.display(),
    );
    ExitCode::SUCCESS
}

/// Run `tree-sitter generate` in `dir` (the build step that turns the widened `grammar.js` into a
/// parser). A missing `tree-sitter` CLI is a hard failure only when the caller asked to build.
fn run_tree_sitter_generate(dir: &Path) -> ExitCode {
    match std::process::Command::new("tree-sitter")
        .arg("generate")
        .current_dir(dir)
        .status()
    {
        Ok(status) if status.success() => {
            eprintln!("noeta grammar: `tree-sitter generate` succeeded.");
            ExitCode::SUCCESS
        }
        Ok(status) => {
            eprintln!("noeta grammar: `tree-sitter generate` failed ({status}).");
            ExitCode::FAILURE
        }
        Err(e) => {
            eprintln!(
                "noeta grammar: could not run `tree-sitter generate` ({e}). Install the tree-sitter CLI and run it in `{}`.",
                dir.display(),
            );
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn names(tiers: &[TierEntry]) -> Vec<&str> {
        tiers.iter().map(|t| t.name.as_str()).collect()
    }

    #[test]
    fn doc_is_always_present_and_maps_to_markdown() {
        let tiers = canonical_tiers([]);
        assert_eq!(names(&tiers), ["doc"]);
        assert_eq!(tiers[0].language.as_deref(), Some("markdown"));
    }

    #[test]
    fn custom_tier_is_included_with_its_language() {
        let tiers = canonical_tiers([("spec".to_string(), Some("xml".to_string()))]);
        assert_eq!(names(&tiers), ["doc", "spec"]);
        let spec = tiers.iter().find(|t| t.name == "spec").unwrap();
        assert_eq!(spec.language.as_deref(), Some("xml"));
    }

    #[test]
    fn output_is_sorted_and_deduplicated_regardless_of_input_order() {
        let a = canonical_tiers([
            ("spec".to_string(), Some("xml".to_string())),
            ("query".to_string(), Some("sql".to_string())),
            ("spec".to_string(), Some("xml".to_string())),
        ]);
        let b = canonical_tiers([
            ("query".to_string(), Some("sql".to_string())),
            ("spec".to_string(), Some("xml".to_string())),
        ]);
        // Same set, different order/multiplicity → identical canonical form (determinism).
        assert_eq!(a, b);
        assert_eq!(names(&a), ["doc", "query", "spec"]);
    }

    #[test]
    fn conflicting_languages_resolve_deterministically_to_the_smallest() {
        // Two declarations for the same tier with different languages must not depend on order.
        let a = canonical_tiers([
            ("spec".to_string(), Some("xml".to_string())),
            ("spec".to_string(), Some("html".to_string())),
        ]);
        let b = canonical_tiers([
            ("spec".to_string(), Some("html".to_string())),
            ("spec".to_string(), Some("xml".to_string())),
        ]);
        assert_eq!(a, b);
        let spec = a.iter().find(|t| t.name == "spec").unwrap();
        assert_eq!(spec.language.as_deref(), Some("html")); // min("html", "xml")
    }

    #[test]
    fn a_language_wins_over_a_bare_verbatim_declaration() {
        // An expression tier (no language) and a text tier (with language) for the same name → the
        // language is kept, order-independently.
        for pair in [
            [
                ("spec".to_string(), None),
                ("spec".to_string(), Some("xml".to_string())),
            ],
            [
                ("spec".to_string(), Some("xml".to_string())),
                ("spec".to_string(), None),
            ],
        ] {
            let tiers = canonical_tiers(pair);
            let spec = tiers.iter().find(|t| t.name == "spec").unwrap();
            assert_eq!(spec.language.as_deref(), Some("xml"));
        }
    }

    #[test]
    fn malformed_identifiers_are_dropped() {
        let tiers = canonical_tiers([
            ("has space".to_string(), Some("xml".to_string())),
            ("1bad".to_string(), Some("xml".to_string())),
            ("ok".to_string(), Some("weird lang".to_string())),
        ]);
        assert_eq!(names(&tiers), ["doc", "ok"]);
        // The malformed language is dropped, but the valid tier name still widens the grammar.
        let ok = tiers.iter().find(|t| t.name == "ok").unwrap();
        assert_eq!(ok.language, None);
    }

    #[test]
    fn project_tiers_json_is_valid_and_deterministic() {
        let tiers = canonical_tiers([("spec".to_string(), Some("xml".to_string()))]);
        let json = project_tiers_json(&tiers);
        // Round-trips as JSON and carries the widened token list.
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        let list: Vec<String> = parsed["textTiers"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect();
        assert_eq!(list, ["doc", "spec"]);
        // Byte-stable across calls.
        assert_eq!(json, project_tiers_json(&tiers));
    }

    #[test]
    fn expr_tiers_list_and_inject_separately_from_text_tiers() {
        let mut tiers = canonical_tiers([("query".to_string(), Some("sql".to_string()))]);
        tiers.extend(canonical_expr_tiers([
            ("greet".to_string(), None),
            ("tmpl".to_string(), Some("html".to_string())),
        ]));

        // The overlay lists text and expression tiers under distinct keys.
        let parsed: serde_json::Value = serde_json::from_str(&project_tiers_json(&tiers)).unwrap();
        let arr = |k: &str| -> Vec<String> {
            parsed[k]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_str().unwrap().to_string())
                .collect()
        };
        assert_eq!(arr("textTiers"), ["doc", "query"]); // `doc` is the std default text tier
        assert_eq!(arr("exprTiers"), ["greet", "tmpl"]);

        // Injection: a text tier maps `text_tier_block`, an expr tier with a segment language maps
        // `expr_tier_block`'s `text_segment`s (holes stay code); a language-less expr tier gets none.
        let scm = injections_scm(&tiers);
        assert!(scm.contains("text_tier_block") && scm.contains("(#eq? @_tier \"query\")"));
        assert!(scm.contains("expr_tier_block") && scm.contains("(#eq? @_tier \"tmpl\")"));
        assert!(!scm.contains("(#eq? @_tier \"greet\")"));
    }

    #[test]
    fn injections_scm_has_one_rule_per_tier_with_a_language() {
        let tiers = canonical_tiers([
            ("spec".to_string(), Some("xml".to_string())),
            ("bare".to_string(), None),
        ]);
        let scm = injections_scm(&tiers);
        assert!(scm.contains("(#eq? @_tier \"doc\")"));
        assert!(scm.contains("(#set! injection.language \"markdown\")"));
        assert!(scm.contains("(#eq? @_tier \"spec\")"));
        assert!(scm.contains("(#set! injection.language \"xml\")"));
        // A tier with no language gets no injection rule (its body still parses verbatim).
        assert!(!scm.contains("@_tier \"bare\""));
        assert_eq!(scm, injections_scm(&tiers)); // deterministic
    }
}
