[package]
name = "lang-lexer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
lang-span = { workspace = true }
lang-diagnostics = { workspace = true }
logos = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[lints]
workspace = true
