//! The **explanation catalog** — the canonical, user-facing description of every diagnostic
//! code, and the single source of truth behind `noeta explain`, the MCP `explain_diagnostic`
//! tool, and the generated `Diagnostics` reference page on the docs site.
//!
//! Prose lives here rather than in the wiki so it cannot drift from the codes it describes:
//! a new [`DiagnosticCode`] does not compile until it has an entry (the `match` below is
//! exhaustive), and the docs page is rendered from `noeta explain --all --format json`.
//!
//! Keep entries short and *actionable*. `summary` is one sentence — what happened. `detail` is
//! the fix, and is empty where the summary already says it. Neither should describe how the
//! language used to behave.

use crate::{DiagnosticCode, Severity};

/// Everything the toolchain can say about one diagnostic code, with no span attached.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Explanation {
    /// The stable wire code, e.g. `"E0059"`.
    pub code: &'static str,
    /// A short human name for the code, e.g. `"shadowed binding"`.
    pub title: &'static str,
    /// The catalog section this code belongs to; see [`GROUPS`] for the render order.
    pub group: &'static str,
    /// Whether emitting this code fails a build.
    pub severity: Severity,
    /// One sentence: what happened.
    pub summary: &'static str,
    /// How to fix it. Empty where `summary` already says it.
    pub detail: &'static str,
    /// The guide page carrying the rule in full, as a wiki slug. Empty where no page covers it.
    pub docs: &'static str,
}

/// The catalog sections, in the order a rendered catalog should present them.
pub const GROUPS: &[&str] = &[
    "Names and scope",
    "Types, inference, and narrowing",
    "Control flow and matching",
    "Functions and calls",
    "Data: structs, classes, enums, fields",
    "Traits, generics, and derives",
    "Errors and results",
    "Modules",
    "Directives, attributes, and tiers",
    "Concurrency and reactivity",
    "Syntax",
    "Runtime failures",
    "Internal",
];

impl DiagnosticCode {
    /// This code's entry in the explanation catalog.
    ///
    /// Exhaustive by construction: adding a [`DiagnosticCode`] variant fails to compile until it
    /// is given an explanation here.
    pub fn explain(self) -> Explanation {
        match self {
            DiagnosticCode::UnknownName => Explanation {
                code: "E0005",
                title: "unknown name",
                group: "Names and scope",
                severity: Severity::Error,
                summary: "A name does not resolve to anything in scope.",
                detail: "The name is not bound in any scope the reference can see. Inside a named `fn` that often means a surrounding value binding: named functions are **sealed** — their bodies see declarations, never enclosing value bindings — so import the binding with a `use (name)` capture clause, or pass it as a parameter.",
                docs: "Functions-and-Closures",
            },
            DiagnosticCode::ImmutableAssignment => Explanation {
                code: "E0006",
                title: "immutable assignment",
                group: "Names and scope",
                severity: Severity::Error,
                summary: "Assignment to an immutable binding — one not declared `mut`.",
                detail: "Immutable is the default. Declare the binding `mut` if it genuinely has to change; otherwise bind a new name.",
                docs: "Syntax-Basics",
            },
            DiagnosticCode::UnresolvedImport => Explanation {
                code: "E0019",
                title: "unresolved import",
                group: "Names and scope",
                severity: Severity::Error,
                summary: "A `use` names something the module does not export, or exports without `pub`.",
                detail: "",
                docs: "Modules",
            },
            DiagnosticCode::NameCollision => Explanation {
                code: "E0020",
                title: "name collision",
                group: "Names and scope",
                severity: Severity::Error,
                summary: "An imported name collides with another top-level name in the file.",
                detail: "",
                docs: "Modules",
            },
            DiagnosticCode::ReservedName => Explanation {
                code: "E0046",
                title: "reserved name",
                group: "Names and scope",
                severity: Severity::Error,
                summary: "A name is already spoken for — a reserved word, or one of the prelude names `Ok`, `Err`, `some`, `none`, `panic`, `assert`.",
                detail: "Three families are reserved: the grammar's keywords, the boolean literals `true`/`false`, and the reflection primitives (`type_name`, `params_of`, `construct`, and the rest). A reserved word is refused wherever a name is bound — a parameter, a binding, a field, a `for` variable, a type or its variants, a generic parameter — because the word has to mean one thing everywhere it appears. Rename the binder; the prelude names are refused for the same reason and shadow nothing.",
                docs: "Syntax-Basics",
            },
            DiagnosticCode::ReservedTypeName => Explanation {
                code: "E0049",
                title: "reserved type name",
                group: "Names and scope",
                severity: Severity::Error,
                summary: "A declaration binds a reserved native type name, such as `Uuid` or `Iterator`.",
                detail: "",
                docs: "",
            },
            DiagnosticCode::ShadowedBinding => Explanation {
                code: "E0059",
                title: "shadowed binding",
                group: "Names and scope",
                severity: Severity::Error,
                summary: "A binder reuses a name that already means something in scope.",
                detail: "One name means one thing per scope stack. Assignment already reassigns rather than re-declaring, and an `is` test narrows the same binding, so shadowing is never needed to express anything — rename the binder.",
                docs: "Syntax-Basics",
            },
            DiagnosticCode::TypeMismatch => Explanation {
                code: "E0007",
                title: "type mismatch",
                group: "Types, inference, and narrowing",
                severity: Severity::Error,
                summary: "A type or arity mismatch — the language's general \"this is not that\" code.",
                detail: "The general \"this is not that\" code, reported wherever a value meets a type it is not assignable to — an argument, a return, a field, an operand, a reassignment. A `mut` binding keeps the type it was declared with, so a reassignment that changes it lands here too: declare a union (`int | string`) or `dyn` for a binding that must hold more than one type.",
                docs: "Syntax-Basics",
            },
            DiagnosticCode::UnknownType => Explanation {
                code: "E0013",
                title: "unknown type",
                group: "Types, inference, and narrowing",
                severity: Severity::Error,
                summary: "A type annotation names a type that does not resolve.",
                detail: "Nothing declares, imports, or builds in a type of that name. Check the spelling, and check that the `use` bringing it in is present — a qualified reference needs its import.",
                docs: "Type-System",
            },
            DiagnosticCode::MissingSignature => Explanation {
                code: "E0022",
                title: "missing signature",
                group: "Types, inference, and narrowing",
                severity: Severity::Error,
                summary: "A named function is missing a parameter or return type.",
                detail: "Signatures are mandatory at named boundaries: every parameter and the return type of a named `fn` must be annotated. Bodies, locals, and closures stay inferred.",
                docs: "Type-System",
            },
            DiagnosticCode::CannotInfer => Explanation {
                code: "E0023",
                title: "cannot infer",
                group: "Types, inference, and narrowing",
                severity: Severity::Error,
                summary: "A binding's type cannot be inferred and is not annotated — `x = []`, `m = {}`.",
                detail: "Nothing determines the element or payload type — `x = []` could be a list of anything. Annotate it (`xs: List<int> = []`), or build it up through a `mut` accumulator whose later writes supply the type.",
                docs: "Type-System",
            },
            DiagnosticCode::InvalidNarrow => Explanation {
                code: "E0028",
                title: "invalid narrowing",
                group: "Types, inference, and narrowing",
                severity: Severity::Error,
                summary: "`.as<T>()` applied to a value whose static type is already concrete — there is nothing dynamic to narrow — or aimed at a fixed-width scalar, which no value carries.",
                detail: "Narrowing converts an open type (`dyn`, a union, a kind-type) back to a checked `?T`; a value with a single known concrete type does not need it. A **fixed-width** target (`i8`…`u64`, `f64`) is refused for the opposite reason: a width is a property of storage, not of a value — every integer width is the same runtime word and an `f64` is a `float` bit for bit — so the narrow could never succeed for any input. Narrow to the base type (`.as<int>()`, `.as<float>()`) and annotate the result where the width is wanted. `f32` is exempt: it is reified at runtime with its own narrowing head. So is a parametrized target like `List<i32>`, whose element width lives in the buffer's schema.",
                docs: "Type-System",
            },
            DiagnosticCode::NonIntegerBitwise => Explanation {
                code: "E0043",
                title: "non-integer bitwise operand",
                group: "Types, inference, and narrowing",
                severity: Severity::Error,
                summary: "A bitwise or shift operator applied to a non-integer operand.",
                detail: "",
                docs: "Fixed-Width-Integers",
            },
            DiagnosticCode::FixedWidthOutOfRange => Explanation {
                code: "E0044",
                title: "fixed-width value out of range",
                group: "Types, inference, and narrowing",
                severity: Severity::Error,
                summary: "A fixed-width integer literal outside its width's range, or two widths mixed in one expression.",
                detail: "",
                docs: "Fixed-Width-Integers",
            },
            DiagnosticCode::ErasedWidthNarrow => Explanation {
                code: "E0063",
                title: "unanswerable width type test",
                group: "Types, inference, and narrowing",
                severity: Severity::Warning,
                summary: "**Warning.** `x is i32`/`x is f64` where the scrutinee's static type does not fix the width — the width is not on the value, so the test cannot be answered. Test the base type.",
                detail: "A width is a property of *storage*, not of a value: every integer width is the same runtime word, and an `f64` is a `float` bit for bit. So once a value is held as `dyn` (or as a union, or as an erased type parameter) its width is gone and no runtime test can recover it. This warns only in that case. Where the scrutinee's static type *does* name a width — `a: i32` then `a is i32` — the checker answers the test itself and folds the constant, with no warning. Test the base type (`x is int`, `x is float`) to ask the question the runtime can answer. `f32` never warns: it is reified, with its own runtime tag. Nor does a container target like `List<i32>`, whose element width lives in the buffer's schema.",
                docs: "Fixed-Width-Integers",
            },
            DiagnosticCode::ImpossibleTypeTest => Explanation {
                code: "E0065",
                title: "impossible type test",
                group: "Types, inference, and narrowing",
                severity: Severity::Warning,
                summary: "**Warning.** `x is T` on an `Option`/`Result` against its payload type — the value's head is `some`/`none`/`Ok`/`Err`, so the test is always false. Take the container apart instead.",
                detail: "An `Option` and a `Result` carry their own runtime head constructor (`some`/`none`, `Ok`/`Err`), so a test against the payload's type can never be true. Take the container apart with `match`, or — for mere presence — compare against `none`.",
                docs: "Type-System",
            },
            DiagnosticCode::NonExhaustiveMatch => Explanation {
                code: "E0011",
                title: "non-exhaustive match",
                group: "Control flow and matching",
                severity: Severity::Error,
                summary: "A `match` does not cover every case and has no catch-all.",
                detail: "Add the missing case, or a `_` catch-all. A **guarded** arm (`pattern if cond`) proves nothing — the checker cannot know the guard is ever true — so a `match` whose only arm for a case is guarded still needs an unguarded one. Matching over `dyn` always needs a `_`; matching over a union does not.",
                docs: "Control-Flow-and-Pattern-Matching",
            },
            DiagnosticCode::LoopControlOutsideLoop => Explanation {
                code: "E0024",
                title: "`break`/`continue` outside a loop",
                group: "Control flow and matching",
                severity: Severity::Error,
                summary: "`break` or `continue` outside any loop.",
                detail: "",
                docs: "Control-Flow-and-Pattern-Matching",
            },
            DiagnosticCode::MatchArmNotValue => Explanation {
                code: "E0055",
                title: "match arm yields no value",
                group: "Control flow and matching",
                severity: Severity::Error,
                summary: "A block-bodied match arm where the `match`'s value is used. Blocks yield no value.",
                detail: "Blocks never yield values, so a block-bodied arm would silently contribute `unit` where a value is expected. Give the arm a value expression, or put the whole `match` in statement position where block arms run for their effects.",
                docs: "Control-Flow-and-Pattern-Matching",
            },
            DiagnosticCode::UnreachableMatchArm => Explanation {
                code: "E0066",
                title: "unreachable match arm",
                group: "Control flow and matching",
                severity: Severity::Error,
                summary: "A match arm after an unguarded catch-all — it can never run.",
                detail: "An earlier unguarded `_` or bare-identifier binding already matches every value, so this arm is dead. Unlike an always-false type test, nothing in the source shows it: the catch-all is spelled exactly like the variant patterns around it. Move the catch-all last, or delete the arm.",
                docs: "Control-Flow-and-Pattern-Matching",
            },
            DiagnosticCode::RequiredAfterOptional => Explanation {
                code: "E0026",
                title: "required after optional",
                group: "Functions and calls",
                severity: Severity::Error,
                summary: "A required parameter follows a defaulted one. Defaults are trailing-only.",
                detail: "",
                docs: "Functions-and-Closures",
            },
            DiagnosticCode::InvalidReceiver => Explanation {
                code: "E0047",
                title: "invalid receiver",
                group: "Functions and calls",
                severity: Severity::Error,
                summary: "A method called through the wrong receiver — an instance method as `Type.m(…)`, a static function on a value, or `T.m(…)` under a bound whose trait does not declare `m` static.",
                detail: "",
                docs: "Generics-and-Traits",
            },
            DiagnosticCode::MissingReturn => Explanation {
                code: "E0048",
                title: "missing return",
                group: "Functions and calls",
                severity: Severity::Error,
                summary: "A non-`void` function can reach the end of its body without returning.",
                detail: "Every path out of a non-`void` function has to produce the declared type. The checker accepts a `return`, a `panic`, an `if`/`else` where both arms do, a `while true` with no `break`, and an exhaustive `match` whose every arm does — nested to any depth. A guarded arm proves nothing.",
                docs: "Functions-and-Closures",
            },
            DiagnosticCode::InvalidTypeArguments => Explanation {
                code: "E0058",
                title: "invalid type arguments",
                group: "Functions and calls",
                severity: Severity::Error,
                summary: "Wrong type arguments in a generic application — a turbofish that cannot apply, a built-in constructor at the wrong arity, or a reflection query over a type parameter no instantiation reaches.",
                detail: "Type arguments bind to the declared parameters in order, one each. The name-keyed reflection queries (`type_name::<T>()`, `field_specs_of::<T>()`, `variants_of::<T>()`, `construct::<T>(…)`, `attributes_of::<T>()`, `roles_of::<E>()`) accept a type **parameter** wherever the instantiation reaches the body: a generic type's parameter rides the receiver in an instance method, and a generic `fn`'s or method's own parameter rides the call site. They refuse it where neither does — a nested `fn`'s own parameter, or a class's parameter inside a nested `fn` that has no receiver — because no per-call channel names it there. `from_bytes::<T>(blob)` refuses a parameter *everywhere*, and for a different reason: it needs the element's packed layout rather than its name, and no channel carries one. Reflect where the type is concrete and pass the result in.",
                docs: "Generics-and-Traits",
            },
            DiagnosticCode::InvalidArgument => Explanation {
                code: "E0061",
                title: "invalid argument",
                group: "Functions and calls",
                severity: Severity::Error,
                summary: "A named argument names no parameter, names one already supplied, or follows a positional with no position left.",
                detail: "A label has to name a parameter the callee actually declares, and no parameter may be filled twice. Once an argument is named, every argument after it must be named too. Labels cannot bind through a function *value* (its type carries only types, not names) or on a built-in method.",
                docs: "Functions-and-Closures",
            },
            DiagnosticCode::MissingField => Explanation {
                code: "E0009",
                title: "missing field",
                group: "Data: structs, classes, enums, fields",
                severity: Severity::Error,
                summary: "An all-fields literal left a declared field unset.",
                detail: "",
                docs: "Structs-Classes-and-Enums",
            },
            DiagnosticCode::ImmutableField => Explanation {
                code: "E0033",
                title: "immutable field",
                group: "Data: structs, classes, enums, fields",
                severity: Severity::Error,
                summary: "Assignment to a field not declared `mut`, or on a receiver with no assignable fields.",
                detail: "",
                docs: "Structs-Classes-and-Enums",
            },
            DiagnosticCode::InvalidIdentityCompare => Explanation {
                code: "E0034",
                title: "invalid identity comparison",
                group: "Data: structs, classes, enums, fields",
                severity: Severity::Error,
                summary: "`===`/`!==` on a non-reference operand. Identity is a `class`-only concept.",
                detail: "",
                docs: "Structs-Classes-and-Enums",
            },
            DiagnosticCode::PrivateField => Explanation {
                code: "E0035",
                title: "private field",
                group: "Data: structs, classes, enums, fields",
                severity: Severity::Error,
                summary: "A private field read, written, or set from outside its declaring type.",
                detail: "A `class`'s fields are private by default. Mark the field `pub` to read it from outside, or reach it through a method. (A value `struct`'s fields are always public, so this never fires for a struct.)",
                docs: "Structs-Classes-and-Enums",
            },
            DiagnosticCode::PrivateMethod => Explanation {
                code: "E0076",
                title: "private method",
                group: "Data: structs, classes, enums, fields",
                severity: Severity::Error,
                summary: "A private method called — or bound as a handle — from outside its declaring type.",
                detail: "A method is private by default in every type kind, exactly as a `class`'s fields are: a type's operations belong to it until it says otherwise. Declare it `pub fn` to make it part of the type's public surface, or reach it through a method that already is. Inside the declaring type's own bodies every method is visible, including on another value of that type. A method that implements a `trait` is public by construction — a trait is an outward contract — and must be written `pub` (E0015).",
                docs: "Structs-Classes-and-Enums",
            },
            DiagnosticCode::RedundantVisibility => Explanation {
                code: "E0077",
                title: "redundant visibility",
                group: "Data: structs, classes, enums, fields",
                severity: Severity::Error,
                summary: "A `pub` on something that is already public — a value `struct`'s field.",
                detail: "A `struct`'s fields are public by construction: it is the value kind, and it has no private state to opt out of. So `pub n: int` restates what `struct` already said, and it implies the fields written without it are private, which is the one thing it must not imply. Drop the word. If some of the type's state should be hidden, make it a `class`, where fields default private and `pub` is the opt-in that decides (E0035). The trait twin of this rule is E0053 — `pub` on a trait's own method, refused for the same reason.",
                docs: "Structs-Classes-and-Enums",
            },
            DiagnosticCode::InvalidPackedType => Explanation {
                code: "E0038",
                title: "invalid packed type",
                group: "Data: structs, classes, enums, fields",
                severity: Severity::Error,
                summary: "`@packed` on a non-struct, or a packed struct with a field that cannot lay out flat.",
                detail: "",
                docs: "Fixed-Width-Integers",
            },
            DiagnosticCode::ValidatedConstruction => Explanation {
                code: "E0060",
                title: "literal built a `@validated` type",
                group: "Data: structs, classes, enums, fields",
                severity: Severity::Error,
                summary: "A `@validated` type built by literal from outside its own methods. Go through a constructor.",
                detail: "A `@validated` type may only be built through a constructor it provides, which runs `validate()` and answers a `Result`. Literal construction stays legal inside the type's own methods, and the decode doors are exempt because they validate automatically.",
                docs: "Validation",
            },
            DiagnosticCode::UnknownTrait => Explanation {
                code: "E0014",
                title: "unknown trait",
                group: "Traits, generics, and derives",
                severity: Severity::Error,
                summary: "An `impl` or `@derive` names a trait that is not known, or at the wrong generic arity.",
                detail: "",
                docs: "Generics-and-Traits",
            },
            DiagnosticCode::InvalidImpl => Explanation {
                code: "E0015",
                title: "invalid impl",
                group: "Traits, generics, and derives",
                severity: Severity::Error,
                summary: "An `impl` does not satisfy the trait it names — a missing method, or one whose signature (arity, types, `async`-ness) disagrees.",
                detail: "",
                docs: "Generics-and-Traits",
            },
            DiagnosticCode::TraitBoundNotSatisfied => Explanation {
                code: "E0025",
                title: "trait bound not satisfied",
                group: "Traits, generics, and derives",
                severity: Severity::Error,
                summary: "A type parameter instantiated with a type that does not satisfy its declared bound.",
                detail: "The bound promises the body may use that trait's operations, so an instantiation that does not satisfy it would break the promise. Either implement the trait for the type (or `@derive` it), or relax the bound.",
                docs: "Generics-and-Traits",
            },
            DiagnosticCode::ConflictingTraitImpl => Explanation {
                code: "E0027",
                title: "conflicting trait impl",
                group: "Traits, generics, and derives",
                severity: Severity::Error,
                summary: "More than one implementation of the same trait for one type.",
                detail: "Coherence allows at most one implementation per (type, trait) pair, counting `@derive(T)`, an in-body `impl T { }`, and a standalone `impl T for Type { }` alike. The diagnostic labels both sites; delete one.",
                docs: "Generics-and-Traits",
            },
            DiagnosticCode::UnderivableTrait => Explanation {
                code: "E0050",
                title: "underivable trait",
                group: "Traits, generics, and derives",
                severity: Severity::Error,
                summary: "A `@derive` the type's fields cannot support — ordering a field kind with no ordering, say.",
                detail: "The derive cannot be built from the type's shape — ordering a field kind that has no ordering, say. Implement the trait by hand, bridge the required member (`@derive(Trait, member: field)`), or delegate through a field (`@derive(Trait, via: field)`).",
                docs: "Derives",
            },
            DiagnosticCode::InvalidTraitDeclaration => Explanation {
                code: "E0053",
                title: "invalid trait declaration",
                group: "Traits, generics, and derives",
                severity: Severity::Error,
                summary: "A malformed `trait` declaration — a duplicate trait name, a collision with a declared type, or a repeated method signature.",
                detail: "",
                docs: "",
            },
            DiagnosticCode::OrphanImpl => Explanation {
                code: "E0070",
                title: "orphan impl",
                group: "Traits, generics, and derives",
                severity: Severity::Error,
                summary: "A standalone `impl Trait for Type` in a package that declares neither the trait nor the type.",
                detail: "An `impl` must live with the trait or with the type. Without that rule a package you never named could attach behavior to two other packages' types, and two such packages would collide as an unfixable conflict. To give a foreign type behavior of your own, wrap it in a type you own — `@derive(Trait, via: field)` writes the newtype for you.",
                docs: "Generics-and-Traits",
            },
            DiagnosticCode::InvalidTry => Explanation {
                code: "E0012",
                title: "invalid `?` propagation",
                group: "Errors and results",
                severity: Severity::Error,
                summary: "`?` on something that is not a `Result` or `Option`, or where the early return has nowhere to go.",
                detail: "`?` is an early return, so the enclosing signature has to be able to carry what it returns: `?T` when the `?` is on an `Option`, `Result<T, E>` when it is on a `Result`. Either declare that return, or handle the value here with `match` or `??`.",
                docs: "Error-Handling",
            },
            DiagnosticCode::TryErrorMismatch => Explanation {
                code: "E0057",
                title: "unconvertible `?` error",
                group: "Errors and results",
                severity: Severity::Error,
                summary: "`?` would propagate an `Err` whose type neither matches the declared error type nor converts into it.",
                detail: "`?` converts a mismatched error only through a declared `impl From<Source>` on the enclosing function's error type — the one implicit conversion position in the language. Declare that conversion, or align the declared error type.",
                docs: "Error-Handling",
            },
            DiagnosticCode::UnhandledError => Explanation {
                code: "E0069",
                title: "unhandled error",
                group: "Errors and results",
                severity: Severity::Error,
                summary: "**Runtime.** An `Err` propagated out of the top level. The program aborts with the error's `message()` and a non-zero exit.",
                detail: "The failure had nowhere left to go. This is the runtime half of the `?` position rule: a declared return is checked statically, while top-level code and a `dyn` return defer to here. It is a legitimate shape for a script entry point — do the work, let a failure stop the program loudly — and it guarantees a broken run can never exit 0 in silence.",
                docs: "Error-Handling",
            },
            DiagnosticCode::ModulePathMismatch => Explanation {
                code: "E0072",
                title: "module path mismatch",
                group: "Modules",
                severity: Severity::Error,
                summary: "A file in a package declares a `namespace`. A derived path cannot be declared.",
                detail: "A module's path is the package's import prefix plus the file's path inside the package, so a declaration could only restate it or contradict it. Delete the line — or, if the two genuinely disagreed, move the file to where the declaration said it lived.",
                docs: "Modules",
            },
            DiagnosticCode::ModulePathCollision => Explanation {
                code: "E0073",
                title: "module path collision",
                group: "Modules",
                severity: Severity::Error,
                summary: "Two files derive the same module path.",
                detail: "One path is one module. This is usually the collapse rule biting: a stem that repeats the directory it sits in lands on the same path as a sibling file. Pick one spelling — either a file or a directory with a root file, not both.",
                docs: "Modules",
            },
            DiagnosticCode::IllegalModulePath => Explanation {
                code: "E0074",
                title: "illegal module path",
                group: "Modules",
                severity: Severity::Error,
                summary: "A directory name or file stem is not a legal module-path segment.",
                detail: "Every directory name and file stem is spelled out in somebody's `use`, so each has to lex as exactly one identifier. Nothing is renamed silently: mapping `my-utils` to `my_utils` behind your back would give one module two spellings.",
                docs: "Modules",
            },
            DiagnosticCode::ShadowedTypeParameter => Explanation {
                code: "E0075",
                title: "shadowed type parameter",
                group: "Traits, generics, and derives",
                severity: Severity::Warning,
                summary: "**Warning.** A method's own `<T>` reuses the name of its enclosing type's `<T>`, so the two cannot be told apart by a reader. Rename one.",
                detail: "The two are different parameters — identity is the declaration site, not the spelling — and the inner one shadows the outer, so the program means what it says and still compiles. What it costs is legibility: inside that method `T` is the method's parameter, the enclosing one is unreachable under any spelling, and a call site like `Repo::<Todo>.label::<User>()` gives a reader no way to tell which is which. A parameter that merely shares a name with a declared type is not this warning.",
                docs: "Generics-and-Traits",
            },
            DiagnosticCode::InvalidAttribute => Explanation {
                code: "E0017",
                title: "invalid attribute",
                group: "Directives, attributes, and tiers",
                severity: Severity::Error,
                summary: "A `#[…]` data attribute is malformed or misused.",
                detail: "",
                docs: "Derives",
            },
            DiagnosticCode::NotAnAttribute => Explanation {
                code: "E0029",
                title: "not an attribute",
                group: "Directives, attributes, and tiers",
                severity: Severity::Error,
                summary: "`#[Foo]` names a type that is not a struct marked `@attribute`.",
                detail: "",
                docs: "Attributes-and-Reflection",
            },
            DiagnosticCode::InvalidAttributeTarget => Explanation {
                code: "E0030",
                title: "invalid attribute target",
                group: "Directives, attributes, and tiers",
                severity: Severity::Error,
                summary: "An attribute attached to a declaration kind it does not permit.",
                detail: "",
                docs: "Attributes-and-Reflection",
            },
            DiagnosticCode::InvalidRole => Explanation {
                code: "E0031",
                title: "invalid role",
                group: "Directives, attributes, and tiers",
                severity: Severity::Error,
                summary: "A malformed `@role` — an unknown role, the wrong count, or a struct that is not itself an attribute.",
                detail: "",
                docs: "Attributes-and-Reflection",
            },
            DiagnosticCode::UnknownDirective => Explanation {
                code: "E0036",
                title: "unknown directive",
                group: "Directives, attributes, and tiers",
                severity: Severity::Error,
                summary: "An `@name` that resolves to nothing: not a built-in directive, not a tier, not one any installed extension declares.",
                detail: "The name resolves to nothing in the directive namespace — not a built-in directive, not a tier, not one any installed extension declares. Usually a typo (the diagnostic offers the nearest real name); otherwise the providing package needs an entry in the manifest's `[directives]` table.",
                docs: "Dev-Tiers",
            },
            DiagnosticCode::InvalidDirectiveArgument => Explanation {
                code: "E0037",
                title: "invalid directive argument",
                group: "Directives, attributes, and tiers",
                severity: Severity::Error,
                summary: "An invalid directive argument — unknown parameter, wrong type, set twice, or supplied to a directive that takes none.",
                detail: "",
                docs: "Dev-Tiers",
            },
            DiagnosticCode::InvalidTierDeclaration => Explanation {
                code: "E0051",
                title: "invalid tier declaration",
                group: "Directives, attributes, and tiers",
                severity: Severity::Error,
                summary: "An invalid `@tier` declaration — a colliding name, a `config` that is not an `@attribute` struct, or a wrong runner signature.",
                detail: "",
                docs: "Extending-Tiers",
            },
            DiagnosticCode::InvalidTierExpression => Explanation {
                code: "E0052",
                title: "invalid tier expression",
                group: "Directives, attributes, and tiers",
                severity: Severity::Error,
                summary: "An expression-tier block misused — a non-`expr:` tier in expression position, or an expression tier in statement position.",
                detail: "",
                docs: "Extending-Tiers",
            },
            DiagnosticCode::InvalidDirectiveSite => Explanation {
                code: "E0054",
                title: "invalid directive site",
                group: "Directives, attributes, and tiers",
                severity: Severity::Error,
                summary: "A directive attached at a site the tier or directive does not permit.",
                detail: "",
                docs: "Attributes-and-Reflection",
            },
            DiagnosticCode::DirectiveExpansionFailed => Explanation {
                code: "E0062",
                title: "directive expansion failed",
                group: "Directives, attributes, and tiers",
                severity: Severity::Error,
                summary: "An extension's directive **expansion hook** failed, or generated code that does not parse. Blamed on the directive.",
                detail: "",
                docs: "The-CLI",
            },
            DiagnosticCode::DroppedTierSetup => Explanation {
                code: "E0071",
                title: "dropped tier-setup statement",
                group: "Directives, attributes, and tiers",
                severity: Severity::Warning,
                summary: "**Warning.** A tier runner left a top-level statement out of the shared setup, and a selected test captures a binding that statement writes.",
                detail: "Every tier case runs as `<shared setup> + <call the tier fn>`, and the setup keeps only top-level work that finishes — so a `server.serve(…)` or an endless loop is dropped rather than blocking the runner. Here a dropped statement writes a binding a selected test captures, so that test would see it unwritten. Move the work into a binding, or into a helper the test calls.",
                docs: "Testing",
            },
            DiagnosticCode::GeneratorMisuse => Explanation {
                code: "E0039",
                title: "generator misuse",
                group: "Concurrency and reactivity",
                severity: Severity::Error,
                summary: "A generator misuse — `yield` outside a generator, a declared return that is not `Iterator<T>`, or a value in a generator's `return`.",
                detail: "",
                docs: "Concurrency",
            },
            DiagnosticCode::AsyncMisuse => Explanation {
                code: "E0040",
                title: "async misuse",
                group: "Concurrency and reactivity",
                severity: Severity::Error,
                summary: "An async misuse — `.await` outside an async context, on a non-future, in a closure, or in a condition or loop head.",
                detail: "`.await` needs an async context and a future. It is rejected inside a **closure** (a closure is a fresh callable, not the enclosing async body) and in an `if`/`while` condition or a `for` iterable, which cannot be hoisted without changing when the head evaluates. Bind the awaited value to a local first.",
                docs: "Concurrency",
            },
            DiagnosticCode::OrphanSpawn => Explanation {
                code: "E0041",
                title: "orphan spawn",
                group: "Concurrency and reactivity",
                severity: Severity::Error,
                summary: "A `spawn` outside any `concurrent { }` scope, or a `spawn`/`isolate` on an operand that is not a future — the callee must be an `async fn`.",
                detail: "",
                docs: "Concurrency",
            },
            DiagnosticCode::NotSend => Explanation {
                code: "E0042",
                title: "value is not `Send`",
                group: "Concurrency and reactivity",
                severity: Severity::Error,
                summary: "A `!Send` value would cross an isolate boundary. Only value types may cross.",
                detail: "Only value types cross an isolate boundary: primitives, `bytes`, tuples, enums, structs of `Send` fields, and containers of those. A `class` has identity and cannot be copied across, and neither can `dyn`. Pass the value-typed data it holds instead.",
                docs: "Concurrency",
            },
            DiagnosticCode::ReactiveCycle => Explanation {
                code: "E0045",
                title: "reactive cycle",
                group: "Concurrency and reactivity",
                severity: Severity::Error,
                summary: "**Runtime.** A reactive update did not converge — an effect keeps changing a signal it depends on.",
                detail: "",
                docs: "Reactivity",
            },
            DiagnosticCode::AwaitCancelled => Explanation {
                code: "E0056",
                title: "await cancelled",
                group: "Concurrency and reactivity",
                severity: Severity::Error,
                summary: "**Runtime.** `.await` on a **cancelled** task. A cancelled task never produces a value; use `h.join()` to observe the outcome.",
                detail: "",
                docs: "Concurrency",
            },
            DiagnosticCode::UnexpectedCharacter => Explanation {
                code: "E0001",
                title: "unexpected character",
                group: "Syntax",
                severity: Severity::Error,
                summary: "The lexer hit a character that cannot start a token.",
                detail: "",
                docs: "",
            },
            DiagnosticCode::UnterminatedString => Explanation {
                code: "E0002",
                title: "unterminated string",
                group: "Syntax",
                severity: Severity::Error,
                summary: "A string literal was opened but never closed.",
                detail: "",
                docs: "",
            },
            DiagnosticCode::UnexpectedToken => Explanation {
                code: "E0003",
                title: "unexpected token",
                group: "Syntax",
                severity: Severity::Error,
                summary: "The parser expected one token and found another. Also what a reflection surface reports when handed the wrong kind of operand.",
                detail: "",
                docs: "",
            },
            DiagnosticCode::UnexpectedEndOfInput => Explanation {
                code: "E0004",
                title: "unexpected end of input",
                group: "Syntax",
                severity: Severity::Error,
                summary: "Input ended while a construct was still open.",
                detail: "",
                docs: "",
            },
            DiagnosticCode::NestingTooDeep => Explanation {
                code: "E0032",
                title: "nesting too deep",
                group: "Syntax",
                severity: Severity::Error,
                summary: "Delimiters nest deeper than the parser supports.",
                detail: "",
                docs: "",
            },
            DiagnosticCode::InvalidStringEscape => Explanation {
                code: "E0064",
                title: "invalid string escape",
                group: "Syntax",
                severity: Severity::Error,
                summary: "A malformed string escape — a `\\xHH` outside ASCII or without two hex digits, or a bad `\\u{…}`.",
                detail: "",
                docs: "",
            },
            DiagnosticCode::DivisionByZero => Explanation {
                code: "E0008",
                title: "division by zero",
                group: "Runtime failures",
                severity: Severity::Error,
                summary: "Integer division or remainder by zero.",
                detail: "",
                docs: "",
            },
            DiagnosticCode::Panic => Explanation {
                code: "E0010",
                title: "panic",
                group: "Runtime failures",
                severity: Severity::Error,
                summary: "A `panic(…)`, a failed `assert`, or a detected deadlock aborted the program.",
                detail: "",
                docs: "Error-Handling",
            },
            DiagnosticCode::IndexOutOfBounds => Explanation {
                code: "E0016",
                title: "index out of bounds",
                group: "Runtime failures",
                severity: Severity::Error,
                summary: "An index addressed a list, string, or `bytes` position out of bounds.",
                detail: "",
                docs: "Standard-Library",
            },
            DiagnosticCode::KeyNotFound => Explanation {
                code: "E0018",
                title: "key not found",
                group: "Runtime failures",
                severity: Severity::Error,
                summary: "`m[k]` addressed a map with a key it does not contain.",
                detail: "",
                docs: "Standard-Library",
            },
            DiagnosticCode::IoError => Explanation {
                code: "E0021",
                title: "IO error",
                group: "Runtime failures",
                severity: Severity::Error,
                summary: "An IO operation failed — reading a path that does not exist, say.",
                detail: "",
                docs: "Standard-Library",
            },
            DiagnosticCode::InternalCompilerError => Explanation {
                code: "E0068",
                title: "internal compiler error",
                group: "Internal",
                severity: Severity::Error,
                summary: "The backend could not compile a program the type checker accepted.",
                detail: "This is a bug in the toolchain, not in your source: the backend could not compile a program the type checker accepted. Please report it with the program that produced it.",
                docs: "",
            },
        }
    }
}
